"""not working tag

Revision ID: 2eefc7483efb
Revises: d188726484d4
Create Date: 2020-05-31 16:25:45.153424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eefc7483efb'
down_revision = 'd188726484d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tag', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
