"""without tag

Revision ID: a3405c413ce7
Revises: 35c2802e5b6a
Create Date: 2020-05-31 14:52:52.177237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3405c413ce7'
down_revision = '35c2802e5b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tag', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
