"""retrying tag

Revision ID: d188726484d4
Revises: 12d56b805228
Create Date: 2020-05-31 16:18:02.511144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd188726484d4'
down_revision = '12d56b805228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tag', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'tag')
    # ### end Alembic commands ###
